# PUBKEY=$(cat ~/.ssh/id_ed25519.pub)
# TITLE="Manwe"

# # Check if key already exists
# EXISTS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
#     https://api.github.com/user/keys | jq --arg key "$PUBKEY" '.[] | select(.key == $key)')

# if [ -z "$EXISTS" ]; then
#   echo "Key not found. Adding..."
#   curl -H "Authorization: token $GITHUB_TOKEN" \
#        -H "Content-Type: application/json" \
#        -X POST \
#        -d "{\"title\":\"$TITLE\",\"key\":\"$PUBKEY\"}" \
#        https://api.github.com/user/keys
# else
#   echo "Key already exists. Skipping."
# fi

- name: Read public SSH key
  ansible.builtin.slurp:
    src: ~/.ssh/id_ed25519.pub
  register: pubkey_raw

- name: Add SSH key to GitHub
  community.general.uri:
    url: https://api.github.com/user/keys
    method: POST
    headers:
      Authorization: "token {{ github_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      title: "{{ inventory_hostname }}"
      key: "{{ pubkey_raw['content'] | b64decode }}"
    status_code: 201
  when: pubkey_raw['content'] is defined
