---
- block:
  - name: python3-psycopg2 
    ansible.builtin.apt:
      pkg: python3-kubernetes
      
  - name: create redis namespace
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: redis
  
  - name: copy redis files to tmp
    ansible.builtin.copy:
      src: files/{{ item }}
      dest: /tmp/
    loop: "{{ files }}"

  - name: create redis 
    kubernetes.core.k8s:
      state: present
      src: /tmp/{{ item }}
    loop: "{{ files }}"
  
  - name: cleanup redis files
    ansible.builtin.file:
      path: /tmp/{{ item }}
      state: absent
    loop: "{{ files }}"

      
  when: inventory_hostname in groups['prime']