# bits: 4096 - default for community.cypto.x509_certificate
# type: RSA  - default for community.cypto.x509_certificate
# defaults: country: US
# defaults: state: Virginia
# defaults: locality:  Lovettsville
# defaults: organization: Sierra Lane
# defaults: organizational_unit: Infrastructure Services
# defaults: owner: ubuntu
# defaults: group: ubuntu
# defaults: mode: '0600'
# required: server_key_path  = 'fully qualified path (directory/filename)'
# required: server_cert_path = 'fully qualified path (directory/filename)'
---
- name: set server_name
  ansible.builtin.set_fact:
    server_name: "{{ inventory_hostname }}"

- name: set server_ip
  ansible.builtin.set_fact:
    server_ip: "{{ hostvars[inventory_hostname]['ansible_host'] }}"

# Need the AKI (equal to the CA's SKI) for the CSR
- name:  Get info for CA Certificate
  community.crypto.x509_certificate_info:
    path: /usr/local/share/ca-certificates/ca.crt
  register: result

- name: set authority_key_identifier
  ansible.builtin.set_fact:
    aki: "{{ result.subject_key_identifier }}"

- name: Create private key for new certificate on server
  community.crypto.openssl_privatekey:
    path: "{{ server_key_path }}"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "{{ mode }}"
  run_once: true

- name: Create certificate signing request (CSR) for new certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ server_key_path }}"
    ### (optional) Subject keys
    country_name: "{{ country }}"
    state_or_province_name: "{{ state }}"
    locality_name: "{{ locality }}"
    organization_name: "{{ organization }}"
    organizational_unit_name: "{{ organizational_unit }}"
    ### End (optional) Subject keys
    common_name: "{{ server_name }}"  ## (required) Subject key
    key_usage:
      - digitalSignature
      - keyEncipherment               ## Vault requirement
    key_usage_critical: true
    subject_alt_name:
      - "DNS:{{ server_name }}"
      - "DNS:{{ server_name }}.local"
      - "IP:{{ server_ip }}"          ## Vault requirement
      - "IP:127.0.0.1"
    subject_alt_name_critical: true   ## Vault requirement
    authority_key_identifier: "{{ aki }}"
  run_once: true
  register: csr

- name: Check whether certificate exists
  ansible.builtin.stat:
    path: "{{ server_cert_path }}"
  run_once: true
  register: certificate_exists

- name: Read existing certificate if exists
  ansible.builtin.slurp:
    src: "{{ server_cert_path }}"
  when: certificate_exists.stat.exists
  run_once: true
  register: certificate

- name: Sign certificate with our CA
  community.crypto.x509_certificate_pipe:
    content: "{{ (certificate.content | b64decode) if certificate_exists.stat.exists else omit }}"
    csr_content: "{{ csr.csr }}"
    provider: ownca
    ownca_path: "{{ ca_base_path }}/{{ ca_cert_name }}"
    ownca_privatekey_path: "{{ ca_base_path }}/{{ ca_key_name }}"
    ownca_not_after: +365d  # valid for one year
    ownca_not_before: "-1d"  # valid since yesterday
  delegate_to: localhost          # or whatever host holds the certificate_authority
  run_once: true
  register: certificate

- name: Write certificate file on server_1
  ansible.builtin.copy:
    content: "{{ certificate.certificate }}"
    dest: "{{ server_cert_path }}"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "{{ mode }}"
  run_once: true
  when: certificate is changed