---
node: iluvatar     # Ilúvatar
# vars: api_user:                            from (encrypted) variables
# vars: api_password:                        from (encrypted) variables
# vars: sha:                                 from (encrypted) variables
# hostname as {{ item }}                     from inventory REQUIRED
# vmid     as {{ hostvars[item]['vmid'] }}   from inventory _otherwise_ next available
# ip       as hostvars[item]['ansible_host'] from inventory _otherwise_ DHCP
images:
  ubuntu:
    baseurl: https://cloud-images.ubuntu.com/noble/current/
    target: noble-server-cloudimg-amd64.img
  debian:
    baseurl: https://cloud.debian.org/images/cloud/trixie/latest/
    target: debian-13-genericcloud-amd64.qcow2

user: ubuntu  # to make my ansible/sshing simpler
ostype: l26   
## virtual hardware specs
cores: 2
cpulimit: 2
cputype: host
balloon: 1024
memory: 2048
## network
bridge: vmbr0
gateway: 192.168.86.1
dns_servers: 192.168.86.1 8.8.8.8
nettype: virtio
netinf: "{{ nettype }},bridge={{ bridge }}"
# ifname: eth0
## root disk
scsinf: virtio-scsi-pci
diskpool: ssd_pool
rootdisksize: 20G
# diskincrement: +146.5G    # base image is ~ 3.5G - this is the amount to ADD to the boot disk
bootdiskname: scsi0
bootorder: "{{ bootdiskname }}"
## options
agent: enabled=1
protection: false
##resource pool
pool: Mirkwood
## fixed image parameters
image_path: /root/
