# roles/proxmox-provision/defaults/main.yaml
node: iluvatar                              # proxmox node and api_host
# api_user:                                  from (encrypted) variables  vm tasks require root@pam
# api_password:                              from (encrypted) variables
# sshkey:                                    from (encrypted) variables  
# (required) host_group: an inventory group, role will create a vm or container for each
# hostname as {{ item }}                     from inventory REQUIRED
# vmid     as {{ hostvars[item]['vmid'] }}   from inventory _otherwise_ next available
# ip       as hostvars[item]['ansible_host'] from inventory _otherwise_ DHCP

user: ubuntu
## distribution
vmostype: l26
lxcostype: ubuntu   # or debian
## virtual hardware specs
cores: 2
cpuunits: 100
cpulimit: 2
cputype: host                                         # vm only
lxcmemory: 2048
lxcswap: 0
vmballoon: 1024
vmmemory: 2048
## network
bridge: vmbr0
gateway: 192.168.86.1
dns_servers: 192.168.86.1 8.8.8.8
nettype: virtio                                       # vm only
netinf: "{{ nettype }},bridge={{ bridge }}"           # vm only
## root disk
scsinf: virtio-scsi-pci                               # vm only
diskpool: ssd_pool
lxcrootsize: 10
vmrootdisksize: 20G
bootdiskname: scsi0
bootorder: "{{ bootdiskname }}"
## vm options
agent: enabled=0
protection: false
## lxc options (not sure why there is not one for 'protection'?)
unprivileged: true
onboot: false
## resource pool
pool: Mirkwood

### vm images
vmimages:
  ubuntu:
    baseurl: https://cloud-images.ubuntu.com/noble/current/
    target: noble-server-cloudimg-amd64.img
  debian:
    baseurl: https://cloud.debian.org/images/cloud/trixie/latest/
    target: debian-13-genericcloud-amd64.qcow2
vmimage_path: /root/
###

### lxc images
##  variable lxc image parameters
lxcimages:
  ubuntu:
    baseurl: https://images.linuxcontainers.org/images/ubuntu/noble/amd64/cloud/
    target: ubuntu-24.04-latest_24.04-2_amd64.tar.xz
  debian:
    baseurl: https://images.linuxcontainers.org/images/debian/trixie/amd64/cloud/
    target: debian-13-latest_13.0_amd64.tar.xz
##
## fixed lxc image fetching parameters - should align with container template
filecomp: rootfs.tar.xz
lxcimage_path: /var/lib/vz/template/cache/
template_base: local:vztmpl/
##
###
## lxc gpu_access variables
gpu_access: false  # set to true if you want to enable GPU access
gpu_config_additions: |
  lxc.cgroup2.devices.allow: c 195:* rwm
  lxc.cgroup2.devices.allow: c 507:* rwm
  lxc.cgroup2.devices.allow: c 510:* rwm

  lxc.mount.entry: /dev/nvidia0 dev/nvidia0 none bind,optional,create=file
  lxc.mount.entry: /dev/nvidiactl dev/nvidiactl none bind,optional,create=file
  lxc.mount.entry: /dev/nvidia-uvm dev/nvidia-uvm none bind,optional,create=file
  lxc.mount.entry: /dev/nvidia-uvm-tools dev/nvidia-uvm-tools none bind,optional,create=file
  lxc.mount.entry: /dev/nvidia-caps dev/nvidia-caps none bind,optional,create=dir
  lxc.mount.entry: /dev/nvidia-caps/nvidia-cap1 dev/nvidia-caps/nvidia-cap1 none bind,optional,create=file
  lxc.mount.entry: /dev/nvidia-caps/nvidia-cap2 dev/nvidia-caps/nvidia-cap2 none bind,optional,create=file