# roles/proxmox-provision/defaults/main.yaml
# api_user: joe@pve                          from vars/main.yaml                      
# api_password: (encrypted)                  from vars/main.yaml
# root_api_user: root@pam                    from vars/main.yaml - "Add boot disk from image for VM" task requires root@pam access
# root_api_password: (encrypted)             from vars/main.yaml - "Add boot disk from image for VM" task requires root@pam access
# bluep_api_password:(encrypted)             from vars/main.yaml
# bluep_root_api_password: (encrypted)       from vars/main.yaml
# sha: []                                    from vars/main.yaml - list of public keys with key type, and meta-data removed
# hostname                                   from inventory REQUIRED
# type                                       from inventory _otherwise_ 'lxc'    (or kvm)
# os                                         from inventory _otherwise_ 'ubuntu' (or debian)
# release                                    from inventory _otherwise_ 'lts'    (or latest)
# vmid                                       from inventory _otherwise_ next available
# static_ip                                  from inventory _otherwise_ DHCP

# node                         # proxmox node and api_host (or bluep)
# user
# ## distribution
# os
# release: lts
# vmostype: l26
# ## virtual hardware specs
# type: lxc
# cores: 2
# cpuunits: 100
# cpulimit: 2
# cputype: host                                         # vm only
# memory: 2048
# swap: 0                                               # lxc only
# maxmemory: 2048                                       # vm only
# ## network
# bridge: vmbr0
# gateway: 192.168.86.1
# dns_servers: 192.168.86.1 8.8.8.8
# nettype: virtio                                       # vm only
# netinf: "{{ nettype }},bridge={{ bridge }}"           # vm only
# ## root disk
# diskpool: ssd_pool
# rootsize: 10
# scsinf: virtio-scsi-pci                               # vm only
# bootdiskname: scsi0                                   # vm only
# ## vm options
# agent: enabled=0
# protection: false
# ## lxc options (not sure why there is not one for 'protection'?)
# unprivileged: true
# onboot: false
# ## resource pool
# pool: Mirkwood
