---
# simply wraps ansible.builtin.apt in a role accepting a single package, or a list of packages
- name: Install apt packages
  ansible.builtin.apt:
    pkg: "{{ packages }}"
    update_cache: yes
    state: present