# host_group: an inventory group, role will create a container for each
node: iluvatar                              # proxmox node and api_host
# api_user:                                  from (encrypted) variables
# api_password:                              from (encrypted) variables
# sshkey:                                    from (encrypted) variables
# hostname as {{ item }}                     from inventory REQUIRED
# vmid     as {{ hostvars[item]['vmid'] }}   from inventory otherwise next available
# ip       as hostvars[item]['ansible_host'] from inventory otherwise DHCP
template: local:vztmpl/ubuntu-24.04-latest_24.04-2_amd64.tar.xz
ostype: ubuntu
cores: 2
cpuunits: 100
cpulimit: 2
memory: 2048
swap: 0
bridge: vmbr0
gateway: 192.168.86.1
diskpool: ssd_pool
rootsize: 10
unprivileged: true
onboot: true
pool: Mirkwood