# Sample ansible playbook demonstrating some functionality in Proxmox-VE
# using the community.general.proxmox_kvm and proxmox_disk modules as
# encpsulated in the two roles included below.

# the first role creates a VM to be the template for the actual hosts to be provisioned
# -- note -- "import image to disk" requires root@pam credentials to import from an absolute path
# the second role makes a series of clones based on the info in 03_host_list.yaml
# -- note -- user@pve PVEAdmin level credentials are sufficient for this role

---
- name: Clear known_hosts
  hosts: localhost
  connection: local
  tasks:
    - name: Loop through hosts removing previous entries from /home/ubuntu/.ssh/known_hosts
      ansible.builtin.shell:
        cmd: "ssh-keygen -f '/home/ubuntu/.ssh/known_hosts' -R {{ item }}"
      loop: "{{ groups['allnodes'] }}"

- name: Provision Proxmox VM hosts
  hosts: pvenode
  become: no
  vars_files:
    - 01_sha_keys.yaml
    - 02_host_list.yaml
  roles:
    - proxmox-template
    - proxmox-clone