---
- name: Provision Proxmox VM hosts
  hosts: pvenode
  become: no
  vars_files:
    - 03_host_list.yaml
  roles:
    # - proxmox-template
    - proxmox-clone

- name: Prepare all nodes (update, install packages, setup microceph and microk8s)
  hosts: allnodes
  become: yes
  vars_files:
    - 02_disk_list.yaml
  roles:
    - update_all
    - postgresql_client
    - python3_packages
    - microceph
    - microk8s

- name: Deploy cluster services (kubegres, redis, tcp_ingresses)
  hosts: prime
  become: no
  roles:
    - kubegres
    - redis
    - tcp_ingresses

- name: Deploy application microservices
  hosts: prime
  become: no
  roles:
    - create_matrix_database
    - github_secret
    - update_secrets
    - deploy_microservices