apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.86.92
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: redis
