- name: Microk8s Configure
  hosts: prime
  become: no
  tasks:
  # microk8s addons
  - name: enable metrics-server
    ansible.builtin.shell: microk8s enable metrics-server

  - name: enable dashboard
    ansible.builtin.shell: microk8s enable dashboard

  - name: enable ingress
    ansible.builtin.shell: microk8s enable ingress

  - name: enable rook-ceph
    ansible.builtin.shell: microk8s enable rook-ceph

  - name: connect microk8s to microceph
    ansible.builtin.shell: sudo -E microk8s connect-external-ceph

  - name: make ceph-rbd the default storage class
    ansible.builtin.shell:
      cmd: kubectl patch storageclass ceph-rbd -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'	

  - name: enable minio
    ansible.builtin.shell: sudo -E microk8s enable minio -s ceph-rbd
  
  - name: undefault microk8s-hostpath storageClass
    ansible.builtin.shell: kubectl patch storageclass microk8s-hostpath -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'

  - name: save dashboard token
    ansible.builtin.shell:
      cmd: kubectl -n kube-system describe secret microk8s-dashboard-token | grep token: > /home/ubuntu/dashboard.token

  - name: copy cluster recipe
    ansible.builtin.copy:
      src: /home/ubuntu/cluster_recipe
      dest: /home/ubuntu/cluster_recipe
