apiVersion: v1
kind: Service
metadata:
  name: nodeapiserver
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 3002
    targetPort: 3002
    name: nodeapiserver
  selector:
    k8s-app: nodeapiserver
