- name: create Proxmox Container and generate TLS keys if desired
  hosts: localhost
  connection: local
  vars:
    host_group: other_container
  roles:
    - role: proxmox-container
    - role: generate_keys
      
- name: Setup Vault
  hosts: other_container
  roles:
    - role: copy_ca_to_host
    - role: update_all
    - role: vault_install
    - role: vault_configure
    - role: vault_initialize

# this is still a raw BOC
# - name: prepare vault for KUBEVAULT
#   hosts: localhost
#   connection: local
#   roles:
#     - role: vault_configure_for_kubevault