- name: Provision Proxmox hosts in inventory
  hosts: localhost
  connection: local
  become: no
  vars_files:
    - 03_host_list.yaml
  roles:
    # - proxmox-template
    - proxmox-clone

- name: Set hostnames on VMs
  hosts: allnodes
  become: yes
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: inventory_hostname
        use: debian

