- name: Prepare all nodes (update, install packages, setup microceph and microk8s)
  hosts: allnodes
  become: yes
  roles:
    # - update_all
    - postgresql_client
    - python3_packages
    - { role: microceph, vars_files: [02_disk_list.yaml] }
    - microk8s