---
- name: role testing book
  hosts: allnodes
  # connection: local
  # gather_facts: no
  # vars_files:
  #   - sha_keys.yaml
  tasks:
    - block:
      - name: Setup microk8s
        include_role:
          name: microk8s
      
      
    - block:
      - name: Deploy kubegres
        include_role:
          name: kubegres
      - name: Deploy redis
        include_role:
          name: redis
      - name: Create tcp ingresses
        include_role:
          name: tcp_ingresses
      when: inventory_hostname in groups['prime']
      become: no