---
- name: create cloud-init.yaml
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars_files:
    - 1ai_cloud_init_vars.yaml
  tasks:
  # - name: set the subnode count
  #   ansible.builtin.set_fact:
  #     subcount: "{{ groups['subnodes'] | length }}"
  - name: copy 1aii_cloud-init.yaml
    ansible.builtin.shell: cp 1aii_cloud_init.yaml 1bii_cloud-init.yaml
  - name: append authorized keys to cloud-init.yaml
    ansible.builtin.lineinfile:
      path: 1bii_cloud-init.yaml
      insertafter: "^    ssh_authorized_keys:"
      line: "    - {{ item }}"
    loop: "{{ sha }}"