---
- name: create roach  user and matrix database
  hosts: prime
  become: no
  vars_files:
    - 4ei_database_password_vars.yaml
  tasks:
    - name: create database
      community.postgresql.postgresql_db:
        login_host: "{{ inventory_hostname }}"
        login_user: postgres
        login_password: "{{ supassword }}"
        name: matrix
    - name: create user
      community.postgresql.postgresql_user:
        login_host: "{{ inventory_hostname }}"
        login_user: postgres
        login_password: "{{ supassword }}"
        name: "{{ matrixuser }}"
        role_attr_flags: SUPERUSER
        db: matrix
        password: "{{ matrixpassword }}"
    - name: grant priviledges on database to user
      community.postgresql.postgresql_privs:
        login_host: "{{ inventory_hostname }}"
        login_user: postgres
        login_password: "{{ supassword }}"
        db: matrix
        privs: ALL
        type: database
        role: "{{ matrixuser }}"