---
- name: kubegres deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: kubegres.reactive-tech.io/v1
      kind: Kubegres
      metadata:
        name: mypostgres
        namespace: kubegres
      spec:
        replicas: 1
        image: postgres:latest
        database:
            size: 200Mi
        env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: mypostgres-secret
                    key: superUserPassword
            - name: POSTGRES_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: mypostgres-secret
                    key: replicationUserPassword