- name: kubectl Configure
  hosts: allnodes
  become: no
  tasks:
  
  - name: create kube directory
    ansible.builtin.file:
      path: /home/ubuntu/.kube
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: '0755'

  - name: create static .kube config
    ansible.builtin.shell:
      cmd: microk8s kubectl config view --raw=true > /home/ubuntu/.kube/config

  - name: .kube/config permissions
    ansible.builtin.file:
      path: /home/ubuntu/.kube/config
      state: touch
      owner: ubuntu
      group: ubuntu
      mode: '0600'
