---
- name: kubegres primary service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: mypostgres
        namespace: kubegres
      spec:
        clusterIP: None
        ports:
        - port: 5432
          targetPort: 5432
          name: mypostgres
        selector:
          app: mypostgres
          replicationRole: primary

- name: kubegres replica service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: mypostgres-replica
        namespace: kubegres
      spec:
        clusterIP: None
        ports:
        - port: 5432
          targetPort: 5432
          name: mypostgres
        selector:
          app: mypostgres
          replicationRole: replica