## virtual hardware specs
cores: 4
cpulimit: 4
cputype: host
vmballoon: 2048
vmmemory: 8192
## root disk
diskpool: nvme_pool
vmrootdisksize: 50G
## options
agent: enabled=1
protection: true
##resource pool
pool: Lothlorien