## virtual hardware specs
cores: 4
cpulimit: 4
cputype: host
balloon: 2048
memory: 8192
## root disk
diskpool: nvme_pool
rootdisksize: 50G
## options
agent: enabled=1
protection: true
##resource pool
pool: Lothlorien