- name: copy base cloud-init
  ansible.builtin.copy:
    src: cloud_init_base.yaml
    dest: "{{ cloud_init }}"

- name: append authorized keys to cloud-init
  ansible.builtin.lineinfile:
    path: "{{ cloud_init }}"
    insertafter: "^    ssh_authorized_keys:"
    line: "    - {{ item }}"
  loop: "{{ sha }}"

- name: provision hosts
  ansible.builtin.shell: 
    cmd: multipass launch -n {{ item }} -c{{ cpus }} -m{{ memory }} -d{{ disk }} --cloud-init {{ cloud_init }}
  loop: "{{ groups['allnodes'] }}"

- name: delete cloud-init with keys
  ansible.builtin.file:
    path: "{{ cloud_init }}"
    state: absent

- name: update /etc/hosts for instances
  include_tasks: inventory_tasks.yaml
  loop: "{{ groups['allnodes'] }}"