---
- name: Install NVidia Container Toolkit installation prequisites 
  ansible.builtin.apt:
      pkg:
      - gpg
      - curl
      state: present
      update_cache: yes

- name: Check if NVidia Container Toolkit apt keyring exists
  ansible.builtin.stat:
    path: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
  register: file_check # Register the output in file_check variable

- name: Add NVidia Container Toolkit apt keyring and apt source if it doesn't exist
  ansible.builtin.shell: |
    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
    curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
  when: not file_check.stat.exists

# Supports packages:
#   - cuda-toolkit-12-9
#   - nvidia-open