---
- name: python3-kubernetes 
  ansible.builtin.apt:
    pkg: python3-kubernetes

- name: create iot namespace 
  kubernetes.core.k8s:
    state: present
    src: "{{ manifest_directory }}/{{ item }}"
  loop: "{{ iot }}"

- name: create mosquitto 
  kubernetes.core.k8s:
    state: present
    src: "{{ manifest_directory }}/{{ item }}"
  loop: "{{ mosquitto }}"

- name: create influxdb
  kubernetes.core.k8s:
    state: present
    src: "{{ manifest_directory }}/{{ item }}"
  loop: "{{ influxdb }}"

- name: create telegraf 
  kubernetes.core.k8s:
    state: present
    src: "{{ manifest_directory }}/{{ item }}"
  loop: "{{ telegraf }}"
