- name: Install node.js prequisites 
  ansible.builtin.apt:
      pkg:
      - curl
      - git
      state: present
      update_cache: yes

- name: get nodesource script
  ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_lts.x -o nodesource_setup.sh

- name: add node repository to apt
  ansible.builtin.shell: bash nodesource_setup.sh
