---
### https://ubuntuhandbook.org/index.php/2024/02/install-python-3-13-ubuntu/ ###
- name: Install Python version from deadsnakes PPA
  ansible.builtin.shell: |
    sudo add-apt-repository -y ppa:deadsnakes/ppa
    sudo apt-get update
    sudo apt-get install -y python{{ python_version }}-full python{{ python_version }}-dev python{{ python_version }}-venv

- name: Ensure pip for the Python version is installed
  ansible.builtin.command: python{{ python_version }} -m ensurepip --upgrade