---
# provision cluster hosts with multipass for virtual machines
- name: Provision Multipass hosts in inventory
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars_files:
    - 01_sha_keys.yaml          # list of SHA-KEYs for authorized hosts [Encrypted]
  roles:
    - role: multipass

# update all nodes, install necessary support packages, and microceph and microk8s snaps
- name: Prepare nodes, setup microceph and microk8s
  hosts: allnodes
  become: yes
  roles:
  - role: update_all
  - role: postgresql_client
  - role: python3_packages
  # - role: snaps  # this seems redundant now?!?

# create microceph cluster
- name: setup microceph
  hosts: allnodes
  become: yes
  # vars_files:
  #   - 02_disk_list.yaml
  roles:
  - role: microceph

# create microk8s cluster
- name: setup microk8s
  hosts: allnodes
  become: yes
  # serial: 1
  roles:
  - role: microk8s

# deploy kubegres and redis to the cluster
- name: Deploy kubegres and redis to the cluster
  hosts: prime
  become: no
  roles:
  - role: kubegres
  - role: redis
  - role: tcp_ingresses

# deploy containers for microservices, apiserver and webdisplay
- name: Prepare nodes, setup microceph and microk8s, deploy kubegres and redis
  hosts: prime
  become: no
  roles:
  - role: create_matrix_database
  - role: github_secret
  - role: copy_deployment_files
  - role: update_secrets
  - role: deploy_microservices
