---
# top-level playbook to provision multipass hosts
# expects 'main host' in group prime (only 1, please), and
# other hosts in group subnodes (0..n), with
- name: Provision Multipass hosts in inventory
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars_files:
    - 1a_cloud_init_vars.yaml          # list of SHA-KEYs [Encrypted]
    - 1b_multipass_provision_vars.yaml # cpus, memory, disk space, base cloud-init [Unencrypted]
  
  tasks:
    - name: copy base cloud-init
      ansible.builtin.shell: cp 1ai_cloud_init.yaml 1bi_cloud-init.yaml

    - name: append authorized keys to cloud-init
      ansible.builtin.lineinfile:
        path: 1bi_cloud-init.yaml
        insertafter: "^    ssh_authorized_keys:"
        line: "    - {{ item }}"
      loop: "{{ sha }}"

    - name: provision hosts
      ansible.builtin.shell: 
        cmd: multipass launch -n {{ item }} -c{{ cpus }} -m{{ memory }} -d{{ disk }} --cloud-init {{ cloud_init }}
      loop: "{{ groups['all'] }}"

    - name: delete cloud-init with keys
      ansible.builtin.file:
        path: ./1bi_cloud-init.yaml
        state: absent

    - name: update /etc/hosts for instances
      include_tasks: 1c_multipass_inventory_tasks.yaml
      loop: "{{ groups['all'] }}"