---
# # top-level playbook to create a multi-node microceph cluster
- name: Microceph
  vars:
    loop_size: 10G
    loop_count: 3
  hosts: allnodes
  become: yes
  tasks:
    - name: Install microceph
      community.general.snap:
        name: microceph
  
    - name: Bootstrap
      ansible.builtin.shell: microceph cluster bootstrap
      when: inventory_hostname in groups['prime']

    - block:
      - name: Generate command to add a new microceph node
        ansible.builtin.shell: "microceph cluster add {{ inventory_hostname }}"
        delegate_to: "{{ groups.prime[0] }}"
        register: result
      - name: join subnodes to the cluster using the returned token
        ansible.builtin.shell: "microceph cluster join {{ result.stdout }}"
      when: inventory_hostname in groups['subnodes']    

    - name: Add Disks
      ansible.builtin.shell: "microceph disk add loop,{{ loop_size }},{{ loop_count }}"