- name: Microk8s Configure
  hosts: prime
  become: no
  tasks:

  - name: copy cluster recipe
    ansible.builtin.copy:
      src: /home/ubuntu/cluster_recipe
      dest: /home/ubuntu

  # kubegres/postgres cluster
  - name: provision kubegres cluster
    ansible.builtin.shell:
      cmd: | 
        kubectl apply -f https://raw.githubusercontent.com/reactive-tech/kubegres/v1.19/kubegres.yaml
        kubectl apply -f kubegres/my-postgres-secret.yaml
        kubectl apply -f kubegres/my-postgres.yaml
        kubectl apply -f kubegres/my-postgres-services.yaml
      chdir: /home/ubuntu/cluster_recipe/

  - name: provision redis
    ansible.builtin.shell:
      cmd: | 
        kubectl apply -f redis/redis-config.yaml
        kubectl apply -f redis/redis-statefulset.yaml
        kubectl apply -f redis/redis-service.yaml
      chdir: /home/ubuntu/cluster_recipe/

  - name: update ingress configmap for kubegres and redis
    ansible.builtin.shell: kubectl patch configmap nginx-ingress-tcp-microk8s-conf -n ingress --type='json' --patch-file /home/ubuntu/cluster_recipe/deployment/cm.json
    # kubernetes.core.k8s_json_patch:
    #   kind: configmap
    #   namespace: ingress
    #   name: nginx-ingress-tcp-microk8s-conf
    #   patch:
    #     - op: add
    #       path: /data/"5432"
    #       value: "kubegres/mypostgres:5432"
    #     - op: add
    #       path: /data/"6379"
    #       value: "redis/redis:6379"

  - name: patch ingress daemonset for kubegres and redis
    ansible.builtin.shell: kubectl patch daemonset nginx-ingress-microk8s-controller -n ingress --type='json' --patch-file /home/ubuntu/cluster_recipe/deployment/ds.json
    # kubernetes.core.k8s_json_patch:
    #   kind: daemonset
    #   namespace: ingress
    #   name: nginx-ingress-microk8s-controller
    #   patch:
    #     - op: add
    #       path: /spec/template/spec/containers/0/ports/-
    #       value: {"name": "kubegres", "hostPort": 5432, "containerPort": 5432, "protocol": "TCP"}
    #     - op: add
    #       path: /spec/template/spec/containers/0/ports/-
    #       value: {"name": "redis", "hostPort": 6379, "containerPort": 6379, "protocol": "TCP"}