---
- name: count subnodes
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:
    - name: set the subnode count
      ansible.builtin.set_fact:
        subcount: "{{ groups['subnodes'] | length }}"

    - name: is zero
      ansible.builtin.debug:
        msg: "subcount: {{ subcount }}"
      when: subcount == "0"

    - name: not zero
      ansible.builtin.debug:
        msg: "subcount: {{ subcount }}"
      when: subcount != "0"