# roles/proxmox-provision/tasks/fetch-lxc-images.yml
- name: "Set base_url and diskimg based for {{ item }}"
  ansible.builtin.set_fact:
    diskimg: "{{ lxcimage_path }}{{ lxcimages[item]['target'] }}"
    base_url: "{{ lxcimages[item]['baseurl'] }}{{ lxcimages[item]['target']}}"

- name: Fetch LXC image index page
  uri:
    url: "{{ lxcimages[item]['baseurl'] }}"
    return_content: yes
  register: lxc_index

- name: Extract all directory names from HTML
  set_fact:
    dir_list: "{{ lxc_index.content | regex_findall('href=\\\"(\\d{8}_\\d{2}%3A\\d{2})/') }}"

- name: Decode and sort directory names
  set_fact:
    sorted_dirs: "{{ dir_list | map('urldecode') | sort }}"

- name: Set latest directory
  set_fact:
    latest_dir: "{{ sorted_dirs[-1] }}"

- name: Download image only if remote is newer
  shell: |
    curl -z {{ diskimg }} -L -o {{ diskimg }} {{ lxcimages[item]['baseurl'] }}{{ latest_dir }}/{{ filecomp }}
  register: curl_result
  changed_when: "'200 OK' in curl_result.stdout or '302 Found' in curl_result.stdout"

- name: Show image update status
  debug:
    msg: "{{ item }} image was updated from remote source."
  when: curl_result.changed
