---
# - name: Install microk8s and kubectl
#   include_tasks: install.yaml

- name: Add subnodes to the cluster
  include_tasks: add_nodes.yaml
  when: "'subnodes' in group_names"

- name: Configure kubectl for user
  import_tasks: make_kubectl_work.yaml

- name: Enable and configure microk8s addons
  include_tasks: configure.yaml
  when: "'prime' in group_names"
