- name: Microk8s add nodes to cluster
  hosts: subnodes
  # vars:
  #   subcount: "{{ groups['subnodes'] | length }}"
  become: no
  tasks:
  
  - name: Generate command to add a new microk8s node
    ansible.builtin.shell: microk8s add-node | grep -m 1 microk8s
    delegate_to: "{{ groups.prime[0] }}"
    become: yes
    register: result
    # when:  subcount != "0"

  - name: add the node to the cluster
    ansible.builtin.shell: "{{ result.stdout }}"
    # when:  subcount != "0"
