- name: Microk8s Configure
  hosts: prime
  become: no
  tasks:
  - name: make kubectl work
    ansible.builtin.shell: |
      mkdir /home/ubuntu/.kube
      microk8s kubectl config view --raw=true > /home/ubuntu/.kube/config
  # microk8s addons
  - name: enable metrics-server
    ansible.builtin.shell: microk8s enable metrics-server

  - name: enable dashboard
    ansible.builtin.shell: microk8s enable dashboard

  - name: enable ingress
    ansible.builtin.shell: microk8s enable ingress

  - name: enable rook-ceph
    ansible.builtin.shell: microk8s enable rook-ceph

  - name: connect microk8s to microceph
    ansible.builtin.shell: sudo -E microk8s connect-external-ceph

  - name: make ceph-rbd the default storage class
    ansible.builtin.command: 
      argv:
        - kubectl 
        - patch 
        - storageClass 
        - ceph-rbd 
        - -p
        - '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

  - name: enable minio
    ansible.builtin.shell: sudo -E microk8s enable minio -s ceph-rbd
  
  - name: undefault microk8s-hostpath storageClass
    ansible.builtin.command: 
      argv:
        - kubectl 
        - patch 
        - storageclass 
        - microk8s-hostpath 
        - -p 
        - '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'

  - name: create dashboard ingress
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /$2
            nginx.ingress.kubernetes.io/configuration-snippet: |
              rewrite ^(/dashboard)$ $1/ redirect;
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
            kubernetes.io/ingress.class: public
          name: dashboard
          namespace: kube-system
        spec:
          rules:
          - http:
              paths:
              - path: /dashboard(/|$)(.*)
                pathType: Prefix
                backend:
                  service:
                    name: kubernetes-dashboard
                    port:
                      number: 443
  
  - name: save dashboard token
    ansible.builtin.shell: kubectl -n kube-system describe secret microk8s-dashboard-token | grep token > /home/ubuntu/dashboard.token
