---
node: iluvatar
vmid: 300
name: cirdan
balloon: 2048
memory: 2048
cores: 2
cpulimit: 2
cputype: host
netinf: virtio,bridge=vmbr0
scsinf: virtio-scsi-pci
diskpool: ssd_pool
diskimg: local:import/ubuntu-24.04-server-cloudimg-amd64.qcow2
bootdiskname: scsi0
ostype: l26
cdrom: "{{ diskpool }}:cloudinit"
bootorder: "{{ bootdiskname }}"
agent: enabled=1
