- name: git clone MagicMirror
  ansible.builtin.shell: git clone https://github.com/MagicMirrorOrg/MagicMirror.git

- name: npm install MagicMirror2
  ansible.builtin.shell: 
    cmd: npm run install-mm 
    chdir: MagicMirror/

- name: Install modules
  include_tasks: add_modules.yaml
  loop: "{{ mmmodules }}"

- name: copy config.js
  ansible.builtin.copy:
    src: config.js
    dest: /root/MagicMirror/config/config.js

- name: copy startup script
  ansible.builtin.copy:
    src: mmso.sh
    dest: /root
    mode: 0755

- name: do pm2 startup
  ansible.builtin.shell: pm2 startup

- name: use pm2 to start server
  ansible.builtin.shell: pm2 start mmso.sh

- name: save pm2 configuration
  ansible.builtin.shell: pm2 save