---
- name: python3-kubernetes
  ansible.builtin.apt:
    pkg: python3-kubernetes
  become: yes
    
- name: Set storage redis class to ceph-rbd, if enabled
  set_fact:
    redis_storage_class: ceph-rbd
  when: ceph_enabled

- name: Apply files/templates
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup(item.type, item.file) }}"
  loop: "{{ k8s_manifest_list }}"
  loop_control:
    label: "{{ item.name | default(item.file) }}"
  when: item.enabled | default(true)
