# roles/proxmox-provision/tasks/main.yaml
- name: Fetch images by type, distro, and release
  ansible.builtin.include_tasks: fetch-image.yaml
  loop: 
    - {type: kvm, os: ubuntu, release: 24}
    - {type: kvm, os: ubuntu, release: 25}
    - {type: kvm, os: debian, release: 12}
    - {type: kvm, os: debian, release: 13}
    - {type: kvm, os: centos, release: 9}
    - {type: kvm, os: centos, release: 10}
    - {type: kvm, os: amazon, release: 2}
    - {type: kvm, os: amazon, release: 2023}
  loop_control:
    label: "{{ item.type }} {{ item.os }} {{ item.release }}"

- name: Show image update summary
  ansible.builtin.debug:
    msg: |
      {% for update in image_updates | default([]) %}
      - {{ update.type }} {{ update.os }} {{ update.release }} → updated at {{ update.timestamp }}
      {% else %}
      No images were updated.
      {% endfor %}

- name: Add changelog header
  ansible.builtin.lineinfile:
    path: /var/log/image-changelog.md
    line: "## {{ ansible_date_time.date }} Image Updates"
    create: yes
    insertafter: EOF
  become: yes
  when: image_updates is defined
  delegate_to: localhost

- name: Append image updates to changelog
  ansible.builtin.lineinfile:
    path: /var/log/image-changelog.md
    line: "- {{ item.timestamp }}: {{ item.type }} {{ item.os }} {{ item.release }} image updated"
    create: yes
    insertafter: EOF
  loop: "{{ image_updates | default([]) }}"
  become: yes
  when: image_updates is defined
  delegate_to: localhost

