---
- name: clean known hosts
  ansible.builtin.shell:
    cmd: "ssh-keygen -f '/home/ubuntu/.ssh/known_hosts' -R {{ item.hostname }}"

- name: clone template to new VM
  community.general.proxmox_kvm:
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ node }}"
    node: "{{ node }}"
    clone: temp
    vmid: "{{ templatevmid }}"  # source (template) VMid
    newid: "{{ item.vmid }}"
    name: "{{ item.hostname }}"
    storage: "{{ diskpool }}"
    pool: Sierra
    state: present

- name: pause for clone to complete
  ansible.builtin.pause:
    seconds: 3

- name: check vm disk size
  community.general.proxmox_vm_info:
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ node }}"
    vmid: "{{ item.vmid }}"
  register: vm_info

- name: Resize boot disk
  community.general.proxmox_disk:
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ node }}"
    vmid: "{{ item.vmid }}"
    disk: "{{ bootdiskname }}"
    size: +26.5G
    state: resized
  when: vm_info.proxmox_vms[0].maxdisk | int < 5000000000  # 5GB - base image  is about 3.5G

- name: Update cloned VM
  community.general.proxmox_kvm:
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ node }}"
    node: "{{ node }}"
    vmid: "{{ item.vmid }}"
    cicustom: "user=local:snippets/userconfig-{{ item.vmid }}.yaml"
    name: "{{ item.hostname }}"
    ipconfig: 
      ipconfig0: "{{ item.ipaddress }}"
    update: true

- name: Start cloned VM
  community.general.proxmox_kvm:
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ node }}"
    node: "{{ node }}"
    vmid: "{{ item.vmid }}"
    state: started
