---
# vars: api_user:      (from encrypted variables)
# vars: api_password:  (from encrypted variables)
# vars: sha:           (from encrypted variables)
api_host: "{{ inventory_hostname }}"
node: "{{ inventory_hostname }}"
pool: Mirkwood
gateway: 192.168.86.1
balloon: 8192
memory: 32768
cores: 8
cpulimit: 8
cputype: host
nettype: virtio
bridge: vmbr0
ifname: eth0
netinf: "{{ nettype }},bridge={{ bridge }}"
scsinf: virtio-scsi-pci
diskpool: nvme_pool
diskimg: /root/noble-server-cloudimg-amd64.img
bootdiskname: scsi0
diskincrement: +146.5G    # base image is ~ 3.5G - this is the amount to ADD to the boot disk
ostype: l26
bootorder: "{{ bootdiskname }}"
agent: enabled=1
protection: false
# fetch_image
base_url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
image_path: /root
target: noble-server-cloudimg-amd64.img
work_dir: /tmp/diskimage_version_tracking
