- name: check if id_rsa.pub exists in ~/.ssh
  ansible.builtin.stat:
    path: /home/ubuntu/.ssh/id_rsa.pub
  register: stat_result

- name: generate ssh keys if they don't exist
  ansible.builtin.shell: 
    cmd: |
      yes y | ssh-keygen -t {{ ssh_key_type }} -b {{ ssh_key_bits }} -N "" -f ~/.ssh/id_rsa > /dev/null
  when: not stat_result.stat.exists