- name: Remove stale SSH keys
  ansible.builtin.shell: ssh-keygen -R {{ item }}
  loop: "{{ groups[host_group] }}"
  
- name: Remove stale SSH keys
  ansible.builtin.shell: ssh-keygen -R {{ hostvars[item].ansible_host | default('') }}
  loop: "{{ groups[host_group] }}"