- name: Remove stale SSH keys
  ansible.builtin.shell: ssh-keygen -R {{ inventory_hostname }}
  ignore_errors: yes
  delegate_to: localhost
  # loop: "{{ groups[host_group] }}"

  
- name: Remove stale SSH keys
  ansible.builtin.shell: ssh-keygen -R {{ ansible_host | default('') }}
  ignore_errors: yes
  delegate_to: localhost
  # loop: "{{ groups[host_group] }}"