- name: Generate command to add a new microk8s node
  ansible.builtin.shell: microk8s add-node | grep -m 1 microk8s
  delegate_to: "{{ groups.prime[0] }}"
  register: result

- name: add the node to the cluster
  ansible.builtin.shell: "{{ result.stdout }}" # --skip-verify"

- name: check node has been added
  ansible.builtin.shell: kubectl get nodes | grep {{ inventory_hostname }}
  delegate_to: "{{ groups.prime[0] }}"
  register: result
  until: result.rc == 0
  retries: 3
  delay: 5


# - ansible.builtin.pause: seconds=10