---
- name: create cloud-init.yaml
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars_files:
    - 1ai_cloud_init_vars.yaml
  tasks:
  - name: create cloud-init.yaml from template
    ansible.builtin.template:
      src: ./1aii_cloud_init.yaml.j2
      dest: ./1bii_cloud-init.yaml
      owner: ubuntu
      group: ubuntu
      mode: '0600'

