- name: Microk8s Configure
  hosts: prime
  become: no
  tasks:
  - name: make kubectl work
    ansible.builtin.shell: |
      mkdir /home/ubuntu/.kube
      microk8s kubectl config view --raw=true > /home/ubuntu/.kube/config
  # microk8s addons
  - name: enable metrics-server
    ansible.builtin.shell: microk8s enable metrics-server

  - name: enable dashboard
    ansible.builtin.shell: microk8s enable dashboard

  - name: enable ingress
    ansible.builtin.shell: microk8s enable ingress

  # - import_playbook: 4ci_microk8s_configure_for_rook_ceph.yaml

  - name: create dashboard ingress
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /$2
            nginx.ingress.kubernetes.io/configuration-snippet: |
              rewrite ^(/dashboard)$ $1/ redirect;
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
            kubernetes.io/ingress.class: public
          name: dashboard
          namespace: kube-system
        spec:
          rules:
          - http:
              paths:
              - path: /dashboard(/|$)(.*)
                pathType: Prefix
                backend:
                  service:
                    name: kubernetes-dashboard
                    port:
                      number: 443
  
  - name: save dashboard token
    ansible.builtin.shell: kubectl -n kube-system describe secret microk8s-dashboard-token | grep token > /home/ubuntu/dashboard.token
