# roles/fetch_vm_image/tasks/main.yml
- name: Get latest file date from ubuntu site
  shell: |
    curl -I {{ base_url }} | grep Last-Modified
  register: dircomp
  changed_when: false

- name: create tmp directory
  ansible.builtin.file:
    path: "{{ work_dir }}"
    state: directory

- name: Save current diskimage version
  copy:
    content: "{{ dircomp.stdout }}"
    dest: "{{ work_dir }}/current_image"

- name: Compare with last_image
  stat:
    path: "{{ work_dir }}/last_image"
  register: latest_image_file

- name: Read last_image if it exists
  slurp:
    src: "{{ work_dir }}/last_image"
  register: latest_image_content
  when: latest_image_file.stat.exists

- name: Set image_is_current fact
  set_fact:
    image_is_current: "{{ latest_image_content.content | b64decode == dircomp.stdout }}"
  when: latest_image_file.stat.exists

- name: Remove old image if new one is available
  file:
    path: "{{ image_path }}/{{ target }}"
    state: absent
  when: not image_is_current | default(false)

- name: Download new image
  get_url:
    url: "{{ base_url }}"
    dest: "{{ image_path }}/{{ target }}"
  when: not image_is_current | default(false)

- name: Update last_image
  copy:
    content: "{{ dircomp.stdout }}"
    dest: "{{ work_dir }}/last_image"
  when: not image_is_current | default(false)