- name: Microceph add nodes to cluster
  hosts: subnodes
  become: yes
  tasks:

  - name: Generate command to add a new microceph node
    ansible.builtin.shell: "microceph cluster add {{ inventory_hostname }}"
    delegate_to: "{{ groups.prime[0] }}"
    register: result

  - name: join subnodes to the cluster using the returned token
    ansible.builtin.shell: "microceph cluster join {{ result.stdout }}"