---
- name: deploy applications to cluster
  hosts: prime
  become: no

  vars_files:
    - 5i_application_containers_vars.yaml

  tasks:
  - name: create github container repository secret
    ansible.builtin.command:
      argv: 
        - kubectl 
        - create 
        - secret 
        - docker-registry 
        - ghcr-login-secret 
        - --docker-server=https://ghcr.io 
        - --docker-username={{ YOUR_GITHUB_USERNAME }} 
        - --docker-password={{ YOUR_GITHUB_TOKEN }}
        - --docker-email={{ YOUR_EMAIL }}

  - name: update matrix-events secret
    ansible.builtin.shell: 
      cmd: python3 update_events.py
      chdir: cluster_recipe/deployment

  - name: update secrets.json secret
    ansible.builtin.shell: 
      cmd: python3 update_secrets.py
      chdir: cluster_recipe/deployment

  - name: deploy microservice servers
    ansible.builtin.shell:
      chdir: cluster_recipe/deployment
      cmd: "kubectl apply -f {{ item }}.yaml"
    with_items:
      - aqi
      - events
      - garmin
      - github
      - mlb
      - moon
      - mycal
      - nfl
      - weather
      - webdisplay
      - webdisplayservice
      - nodeapiserver
      - nodeapiserverservice

