- name: deploy base manifests
  kubernetes.core.k8s:
    state: present
    src: "{{ manifest_directory }}/{{ item }}"
  loop: "{{ base_manifests }}"
  
- name: wait for Grafana pod to be running
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: iot
    label_selectors:
      - app = grafana
  register: pod_list
  until: pod_list.resources | length > 0 and pod_list.resources[0].status.phase == 'Running'
  retries: 30
  delay: 5

- name: Check if grafana.db exists inside the pod yet
  kubernetes.core.k8s_exec:
    namespace: iot
    pod: "{{ pod_list.resources[0].metadata.name }}"
    command: test -f /var/lib/grafana/grafana.db
  register: grafana_db_check
  failed_when: false

- name: Copy grafana.db to backup location
  kubernetes.core.k8s_exec:
    namespace: iot
    pod: "{{ pod_list.resources[0].metadata.name }}"
    command: cp /var/lib/grafana/grafana.db /var/lib/grafana/backup/grafana.db
  when: grafana_db_check.rc == 0

- name: delete step1 deployment manifest
  kubernetes.core.k8s:
    state: absent
    src: "{{ manifest_directory }}/grafana-deployment-step1.yaml"

- name: deploy final deployment manifest
  kubernetes.core.k8s:
    state: present
    src: "{{ manifest_directory }}/grafana-deployment.yaml"