---
# copies ca.crt from Certificate_Authority host to server
# and updates host certificate store

- name: Copy ca.crt to /usr/local/share/ca-certificates
  ansible.builtin.copy:
    src: /home/ubuntu/certificate_authority/ca.crt
    dest: /usr/local/share/ca-certificates/ca.crt

- name: Update the server 'trust store'
  ansible.builtin.shell: update-ca-certificates
