- name: clone one or more repositories
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ local_repo_base_path }}/{{ item.name }}"
  loop: "{{ repositories }}"
  become_user: "{{  local_repo_owner }}"