# bits: 4096 - default for community.cypto.x509_certificate
# type: RSA  - default for community.cypto.x509_certificate
ca_base_path: /home/ubuntu/certificate_authority
ca_key_path: /home/ubuntu/certificate_authority/ca-certificate.key
ca_cert_path: /home/ubuntu/certificate_authority/ca-certificate.pem
country: US
state: Virginia
locality:  Lovettsville
organization: Sierra Lane
organizational_unit: Infrastructure Services
common_name: My CA