---
- name: Create Proxmox-VE Container
  community.general.proxmox:
    api_host: "{{ node }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    node: "{{ node }}"
    vmid: "{{ hostvars[item]['ctid'] }}"
    hostname: "{{ item }}"
    ostemplate: "{{ template }}"
    disk: "{{ rootfs }}"
    # disk_volume:    # requires community.general 9.2.0 or greater
    #   storage: "{{ diskpool }}"
    #   size: "{{ rootsize }}"
    netif:
      net0: "name=eth0,bridge={{ bridge }},ip={{ hostvars[item]['ansible_host'] }}/24,gw={{ gateway }}"
    unprivileged: "{{ unprivileged }}" 
    onboot: "{{ onboot }}"
    pool: "{{ resource_pool }}"
    cores: "{{ cores }}"
    memory: "{{ memory }}"
    swap: "{{ swap }}"
    pubkey: "{{ sshkey }}"
    state: present

- name: Start Container
  community.general.proxmox:
    api_host: "{{ node }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    vmid: "{{ hostvars[item]['ctid'] }}"
    state: started