- name: Prepare Proxmox VM node
  hosts: pvenode
  roles:
    - role: proxmox-node-setup
    - role: proxmox-vm-fetch-image
    - role: proxmox-container-fetch-image

#=== Provision VMs to be microceph/microk8s cluster nodes ===#
- name: Provision Proxmox VM hosts for Kubernetes cluster
  hosts: pvenode
  vars_files:
    - 00_sha_keys.yaml   # structured as a list of keys
    - 00_vm_overrides.yaml
  vars:
    host_group: vms
  roles:
    - role: proxmox-vm-create

# Additional role to create an LXC Container on proxmox using the community.general.proxmox module
- name: create Proxmox Container for Vault
  hosts: pvenode
  vars:
    host_group: lxcs
  roles:
    - role: proxmox-container-create-cloud-init
