---
# 04_cluster.yaml
# Builds a MicroK8s cluster with MicroCeph, configures Vault for KUBEVAULT secrets, and deploys microservices
# Assumes: CA is created, Vault is initialized, and Proxmox VMs are provisioned (all in 00_proxmox.yaml)
- name: Show Ceph status
  debug:
    msg: "Ceph is {{ 'enabled' if ceph_enabled else 'disabled' }}"

- name: Prepare nodes - Part 1 (create microceph cluster and install microk8s)
  hosts: allnodes
  become: yes
  vars_files:
    - 05_disk_list.yaml
  roles:
    - role: certificate-authority-copy-to-host
    - role: apt-add-packages
      vars:
        packages: [ python3-kubernetes, python3-pip, python3-venv ]
    - role: microceph-all                 # only if group_vars-all-ceph_enabled == true
    - role: microk8s-install
      vars:
        new_ca: true       # check for new ca.crt, refresh certs _BEFORE_ making cluster!
                           
- name: Prepare nodes - Part 2 (create microk8s cluster)
  hosts: subnodes
  serial: 1
  become: yes
  roles:
    - role: microk8s-assemble-cluster

- name: Prepare nodes - Part 3 (configure microk8s cluster)
  hosts: allnodes
  become: yes
  roles:
    - role: microk8s-configure   # add task to add IP SANs for kubeapi.local, 192.168.86.90 to the server.crt on each node!

- name: Deploy cluster services (add-ons, pull kubeconfig, redis)
  hosts: prime
  become: no
  roles:
    - role: microk8s-enable-addons       # affected by group_vars-all-ceph_enabled == true
    - role: kubernetes-fetch-config
    - role: kubernetes-redis-deploy      # affected by group_vars-all-ceph_enabled == true
    - role: ghcr-secret-create
    
- name: Configure vault support kubernetes authentication and transit secrets
  hosts: localhost
  become: no
  roles:
    - role: vault-configure-for-kubevault

- name: Deploy application microservices, API and webdisplay
  hosts: prime
  become: no
  roles:
    - role: kubernetes-secrets-bootstrap
    - role: kubernetes-manifests-sync
    - role: kubernetes-microservices-deploy
    - role: kubernetes-mqtt-telegraf-influxdb-deploy
    - role: kubernetes-grafana-deploy

# - name: Deploy other stuff
#   hosts: prime
#   become: no
#   roles:
    # - deploy_open-webui  # Need to write this...