#=== Provision and Configure Vault Container ===

# Additional role to create an LXC Container on proxmox using the community.general.proxmox module
- name: create Proxmox Container for Vault
  hosts: pvenode
  tags: vault:provision
  vars:
    host_group: vault
  roles:
    - role: proxmox-node-setup
    - role: proxmox-container-create

# Creates RFC 2818 compliant TLS certificates with IP SANs (which makes Vault happy)
#   works with Certificate Authority above
- name: TLS keys for server
  hosts: localhost
  tags: vault:configure
  vars:
    host_group: vault
  roles:
    - role: certificate-authority-generate-certs

# wait for the container to settle...
- name: Wait for Container to become reachable
  hosts: vault
  gather_facts: no
  tags: vault:configure
  tasks:
    - name: Wait for SSH to come up
      ansible.builtin.wait_for_connection:
        timeout: 300  # Adjust as needed
        delay: 10     # Initial delay before polling
        sleep: 5      # Time between retries

      
# Adds CA to cert store, installs vault package, 
#   configures vault (TLS Keys and configuration including gcpckms auto-unseal),
#   enables/starts the vault service, and initializes the vault - writing the root token and 
#   unseal keys back to the ansible host
- name: Setup Vault
  hosts: vault
  tags: vault:configure
  roles:
    - role: certificate-authority-copy-to-host
    - role: apt-vault-add-source
    - role: apt-update-all
    - role: apt-add-packages
      vars:
        packages: vault
    - role: vault-configure
    - role: vault-initialize

# kubernetes has to be installed/operational before final role is executed

- name: Configure vault support kubernetes authentication and transit secrets
  hosts: localhost
  become: no
  tags: vault:kubevault
  roles:
    - role: vault-configure-for-kubevault
      vars:
        kubeapiaddress: https://192.168.86.3:16443
        role: demo
        policy: my-app-policy
        transit_key: aes256-key