# 10_magicmirror.yaml
# Provisions a Proxmox container and installs MagicMirror² with Node.js and PM2
# Assumes: Vault and CA are already configured, container image is available

#=== Create Proxmox container for MagicMirror2 ===
- name: Create Proxmox container
  hosts: pvenode
  tags: magicmirror:provision
  vars:
    host_group: magicmirror
  roles:
    - role: proxmox-container-create
      
      
# performs apt update && apt upgrade; install node.js (LTS); clones and installs MagicMirror2 and defined modules
- name: Setup MagicMirror2
  hosts: magicmirror
  tags: magicmirror:install
  roles:
    - role: apt-nodejs-add-source
    - role: apt-update-all
    - role: apt-add-packages
      vars:
        packages: nodejs
    - role: nodejs-pm2-install
    - role: magic-mirror-install

# performs apt update && apt upgrade; pulls and updates MagicMirror2 and defined modules
- name: Update MagicMirror2
  hosts: magicmirror
  tags: magicmirror:update
  roles:
    - role: apt-update-all
    - role: magic-mirror-update