# 77_vscodeserver.yaml
# Provisions a Proxmox container and installs VS Code Server dependencies, CLI tools, and Git config
# Assumes: Vault and CA are already configured, container image is available

- name: create Proxmox Container
  hosts: iluvatar
  vars:
    host_group: valar
    rootsize: 50
  roles:
    - role: proxmox-node-setup
    - role: proxmox-container-fetch-image
    - role: proxmox-container-create-cloud-init
      
- name: Setup Code Server - Part 1 - Update and Install
  hosts: manwe
  become: yes
  roles:
    - role: apt-nodejs-add-source
    - role: apt-vault-add-source
    - role: apt-update-all
    - role: apt-add-packages
      vars:
        packages: [build-essential, curl, git, git-filter-repo, gpg, tree, unzip, wget, 
                  python3-ansible, python3-proxmoxer, python3-kubernetes, python3-pip, python3-venv, pipx
                  nodejs, vault]
    - role: kubernetes-kubectl-install

- name: Setup Code Server - Part 2 - create ssh keys and git config
  hosts: manwe
  become: no
  roles:
    - role: host-ssh-keys-create
    - role: git-global-configure  
    - role: git-add-sshkey     # will need to inject GITHUB_TOKEN to add the new ssh-key to github
    - role: git-clone-repositories