- name: Provision Proxmox guests
  hosts: all
  gather_facts: false
  tasks:
    - name: Include LXC role
      ansible.builtin.include_role:
        name: provision_lxc
      when: hostvars[inventory_hostname].type == "lxc"

    - name: Include KVM role
      ansible.builtin.include_role:
        name: provision_kvm
      when: hostvars[inventory_hostname].type == "kvm"

    - name: Skip other types
      ansible.builtin.debug:
        msg: "Skipping {{ inventory_hostname }} (type={{ hostvars[inventory_hostname].type }})"
      when: hostvars[inventory_hostname].type not in ["lxc", "kvm"]