#=== Provision and Configure Vault Container ===

# Additional role to create an LXC Container on proxmox using the community.general.proxmox module
- name: create Proxmox Container for Vault
  hosts: iluvatar
  tags: vault:provision
  vars:
    host_group: vault
  roles:
    - role: proxmox-container-create-cloud-init
    - role: known-hosts-clear

# wait for the container to settle...
- name: Wait for Container to become reachable
  hosts: moria
  tags: vault:provision
  gather_facts: false
  tasks:
    - name: Wait for SSH to come up
      ansible.builtin.wait_for_connection:
        timeout: 300  # Adjust as needed
        delay: 5     # Initial delay before polling
        sleep: 5      # Time between retries

# Adds CA to cert store, 
#   creates RFC 2818 compliant TLS certificates with _critical_IP SANs (which makes Vault happy)
#   installs vault package, 
#   configures vault (TLS Keys and configuration including gcpckms auto-unseal),
#   enables/starts the vault service, and initializes the vault 
#       - writing the root token and unseal keys back to the ansible host
- name: Setup Vault
  hosts: moria
  tags: vault:setup
  become: true
  roles:
    - role: certificate-authority-copy-to-host
    - role: apt-add-source-vault
    - role: apt-update-all
    - role: apt-add-packages
      vars:
        packages: vault
    - role: certificate-authority-generate-certs
      vars:
        server_key_path: /opt/vault/tls/vault.key
        server_cert_path: /opt/vault/tls/vault.crt
        owner: vault
        group: vault
        mode: '0600'
    - role: vault-configure
    - role: vault-initialize