#=== Provision and Configure Vault Container ===

# Additional role to create an LXC Container on proxmox using the community.general.proxmox module
- name: create Proxmox Container for Vault
  hosts: iluvatar
  vars:
    host_group: vault
  roles:
    - role: proxmox-container-create

# Adds CA to cert store, 
#   creates RFC 2818 compliant TLS certificates with IP SANs (which makes Vault happy)
#   installs vault package, 
#   configures vault (TLS Keys and configuration including gcpckms auto-unseal),
#   enables/starts the vault service, and initializes the vault 
#       - writing the root token and unseal keys back to the ansible host
- name: Setup Vault
  hosts: moria
  roles:
    - role: certificate-authority-copy-to-host
    - role: certificate-authority-generate-certs
      vars:
        server_key_path: /opt/vault/tls/vault.key
        server_cert_path: /opt/vault/tls/vault.crt
        owner: vault
        group: vault
        mode: '0600'
    - role: apt-vault-add-source
    - role: apt-update-all
    - role: apt-add-packages
      vars:
        packages: vault
    - role: vault-configure
    - role: vault-initialize

# # wait for the container to settle...
# - name: Wait for Container to become reachable
#   hosts: moria
#   gather_facts: no
#   tasks:
#     - name: Wait for SSH to come up
#       ansible.builtin.wait_for_connection:
#         timeout: 300  # Adjust as needed
#         delay: 10     # Initial delay before polling
#         sleep: 5      # Time between retries

# # Adds CA to cert store, installs vault package, 
# #   configures vault (TLS Keys and configuration including gcpckms auto-unseal),
# #   enables/starts the vault service, and initializes the vault - writing the root token and 
# #   unseal keys back to the ansible host
# - name: Setup Vault
#   hosts: moria
#   roles:
#     - role: certificate-authority-copy-to-host
#     - role: apt-vault-add-source
#     - role: apt-update-all
#     - role: apt-add-packages
#       vars:
#         packages: vault
#     - role: vault-configure
#     - role: vault-initialize