- name: Wait for VMs to become reachable
  hosts: vmtest
  gather_facts: no
  tasks:
    - name: Wait for SSH to come up
      ansible.builtin.wait_for_connection:
        timeout: 300  # Adjust as needed
        delay: 10     # Initial delay before polling
        sleep: 5      # Time between retries
