# .github/workflows/lint.yml
name: Ansible Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Ansible
        run: pip install ansible ansible-lint
      - name: Run ansible-lint
        run: ansible-lint playbooks/