- name: check if id_rsa.pub exists in ~/.ssh
  ansible.builtin.stat:
    path: /home/ubuntu/.ssh/id_rsa.pub
  register: stat_result

- name: generate ssh keys if they don't exist
  ansible.builtin.shell: ssh-keygen -t rsa -b 2048 -q
  when: not stat_result.stat.exists