- name: make kubectl work after cluster is formed
  ansible.builtin.shell: |
    mkdir /home/ubuntu/.kube
    microk8s config > /home/ubuntu/.kube/config
    chown -R ubuntu:ubuntu /home/ubuntu/.kube

# update server.conf.template to add additional IP SANs
- name: Update csr.conf.template
  ansible.builtin.lineinfile:
    path: /var/snap/microk8s/current/certs/csr.conf.template
    insertbefore: "IP.1 = 127.0.0.1"
    line: "DNS.6 = {{ kubeapidns }}"

- name: Update csr.conf.template
  ansible.builtin.lineinfile:
    path: /var/snap/microk8s/current/certs/csr.conf.template
    insertbefore: "#MOREIPS"
    line: "IP.3 = {{ kubeapiip }}"

# tell microk8s to regenerate server certs
- name: Regenerate new server.crt with additional SANs
  ansible.builtin.shell: 
    cmd: microk8s refresh-certs --cert server.crt
    chdir: /var/snap/microk8s/current/certs/

- name: reboot for group changes to take effect
  ansible.builtin.reboot: